DROP DATABASE twitterdb;
CREATE DATABASE twitterdb;

#CREATE USER 'twitterUser'@'localhost' IDENTIFIED BY 'jakieshaslodotwittera';
#GRANT ALL PRIVILEGES ON twitterdb. * TO 'twitterUser'@'localhost';

USE twitterdb;

CREATE TABLE USER (
  ID BIGINT PRIMARY KEY NOT NULL,
  RAW_DATA TEXT NOT NULL,
  NAME VARCHAR(40) NOT NULL,
  SCREEN_NAME VARCHAR(40) NOT NULL,
  DESCRIPTION TEXT,
  PROFILE_IMAGE_URL TEXT,
  URL TEXT,
  VERIFIED BOOLEAN,
  FAVOURITES_COUNT INT,
  FOLLOWERS_COUNT INT,
  FRIENDS_COUNT INT
);

CREATE TABLE TWEET (
  ID BIGINT NOT NULL PRIMARY KEY,
  RAW_DATA TEXT NOT NULL,
  TWEET_TEXT TEXT NOT NULL,
  CREATE_DATE DATE NOT NULL,
  USER_ID BIGINT NOT NULL,
  RETWEET_COUNT INT,
  RETWEETED BOOLEAN,
  IN_REPLY_TO_USER_ID BIGINT,

  INDEX par_ind (USER_ID),
  FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON DELETE CASCADE,
  FOREIGN KEY (IN_REPLY_TO_USER_ID) REFERENCES USER(ID) ON DELETE CASCADE
);

CREATE TABLE HASHTAGS (
  TWEET_ID BIGINT,
  HASHTAGS TEXT NOT NULL
);

CREATE TABLE USER_MENTIONS (
  TWEET_ID BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL,
  FOREIGN KEY (TWEET_ID) REFERENCES TWEET(ID) ON DELETE CASCADE,
  FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON DELETE CASCADE
);
