CREATE DATABASE twitterdb;

CREATE USER 'twitterUser'@'localhost' IDENTIFIED BY 'jakieshaslodotwittera';
GRANT ALL PRIVILEGES ON twitterdb. * TO 'twitterUser'@'localhost';

USE twitterdb;

CREATE TABLE USER (
    ID BIGINT NOT NULL,
    NAME VARCHAR(40) NOT NULL,
    SCREEN_NAME VARCHAR(40) NOT NULL,
    DESCRIPTION TEXT,
    PROFILE_IMAGE_URL TEXT,
    URL TEXT,
    VERIFIED BOOLEAN,
    FAVOURITES_COUNT INT,
    FOLLOWERS_COUNT INT,
    FRIENDS_COUNT INT,
    PRIMARY KEY (ID)
);

CREATE TABLE TWEET (
    ID BIGINT NOT NULL,
    TWEET_TEXT TEXT NOT NULL,
    CREATE_DATE DATE NOT NULL,
    USER_ID INT,
    INDEX par_ind (USER_ID),
  	FOREIGN KEY (USER_ID) 
    	REFERENCES USER(ID)
        	ON DELETE CASCADE
);
